### PR TITLE
Roadmap and FAQ section

### PR DESCRIPTION
**Pull request by hollisticated-horse**
Pull request to add the **roadmap** page and **faq** page, as well as a few esthetical improvements in the about and support page.

### Plugin/Dependency :
- @tailwindcss/forms

## TODO:

- [ ] center roadmap page
- [ ] github api link for roadmap // maybe get labels for features in releases, or when the Projects api is stable...
- [ ]  add content in about page, like photos or screenshots, or maybe a few illustrations
- [ ] faq content
- [ ] blog
- [ ] shop
- [ ] screenshots
- [ ] video
- [ ] responsive design

### Next Pull-request:
- blog
- minor improvements
- faq sections with collapsable behavior

### CODE REVIEW

**Comment by hollisticated-horse** [comment]
The mobile version of the roadmap page is also buggy because of a margin problem.
I'll try to get that sorted out.

**Comment by ereio** [comment]
@hollisticated-horse looks like node_modules and other ignored directories got included in this PR. dm me and we'll work together to remove them before I'll pull and start making changes 👍

**Comment by hollisticated-horse** [comment]
Hey @ereio, im having issues with my synapse server. Hopefully it'll unblock itself soon. But in the mean time i'm stuck.
How do I remove node_modules for it ?

Is it possible to update a pull request ?

**Comment by hollisticated-horse** [comment]
hey @ereio, in roadmap there is twice token authentication in 0.2.0. Missed that one.

**Comment by ereio** [comment]
pushed again without Token Authentication in both places. Not sure that's necessarily a feature. Thanks for the heads up

**Pull request merged**
