### PR TITLE
Added Flathub button

### PR DESCRIPTION
**Pull request by Danik1601**
Added flathub button to the website (just like in https://github.com/syphon-org/syphon/pull/692) in order to match the current readme.md of the [Syphon](https://github.com/syphon-org/syphon) project.

I sucessfully tested this but still not sure if I didn't broke something, so please do your own testing.

- Flathub button added
- Style fixes for buttons
- App Store link changed to the international format

### CODE REVIEW

**Comment by Danik1601** [comment]
Seems like I have to wait for https://github.com/syphon-org/landing/pull/25 to be merged first. But I will still mark this as ready for review. Just mention me if there will be problems.

**Comment by Danik1601** [comment]
@ereio

**Review by ereio — APPROVED** [review]

**Comment by ereio** [comment]
awesome, thanks so much! :)

**Comment by Danik1601** [comment]
Seems to be reverted by https://github.com/syphon-org/landing/commit/e985eacf6c413ac4b61f77449fd2092a92365265

**Pull request merged**
